name: AI Adoption Report

# if you don't need the GITHUB token
permissions: {}
# if you need read access to repo:
# permissions: read-all 
# if you need write access then this should be inside the respective job

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    # passing inputs to build break SLSA contract - builds need to fully
    # repeatable by the same code
    # if we ever what to implement SLSA this would need to be gone
    inputs:
      pr_number:
        description: 'PR number to analyze'
        required: true
        type: number

jobs:
  ai-adoption:
    uses: vonage-technology/api-ept-ai-forge/.github/workflows/ai-adoption-v2.yml@main
    # example granural permissions
    permissions:
      models: read
    secrets: inherit
